# .github/workflows/test.yml

name: CLI

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Install inso
        uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Run test suites
        run: inso run test uts_26b2ef --verbose
      - name: Generate declarative config
        run: inso generate config "Unity" --type declarative --ci
c
